### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:352)

### ISSUE THREAD

**Issue by zhuwei** [cloudwebrtc/dart-protoo-client#1]
你好，请问https怎么解决。。
`I/flutter (17295): [protoo-client] DEBUG: emit "error" [currentAttempt:HandshakeException: Handshake error in client (OS Error:
I/flutter (17295): 	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:352))]`

**Comment by cloudwebrtc** [comment]
可以修改源码使用  _connectForSelfSignedCert 方法发起ws连接
https://github.com/cloudwebrtc/dart-protoo-client/blob/master/lib/src/transports/WebSocketTransport.dart#L66
连接之前将 wss:// 修改成https://

**Comment by zhuwei** [comment]
@cloudwebrtc 解决了！非常感谢！！！
