### ISSUE TITLE
Regarding further maintainence of the package

### ISSUE THREAD

**Issue by ritvij14** [cloudwebrtc/dart-protoo-client#3]
Will this package be maintained further? I am working on a project that requires usage of protoo-client with latest features available. For now we are using https://github.com/ZackMitkin/dart-protoo-client, a fork of this repository, but soon we will need to publish our package so we won't be able to use it directly from github.

**Comment by cloudwebrtc** [comment]
@ritvij14 Hey, if the author of ZackMitkin/dart-protoo-client is willing, he can push a PR to the original repo, I am happy to accept it, I can also add @ZackMitkin to project members and pub uploader.

Please leave a message after this comment :).

**Comment by ZackMitkin** [comment]
@cloudwebrtc, my version of dart-protoo-client was more of a hack to get mediasoup demo server working for https://github.com/Blancduman/mediasoup-client-flutter. I'm not intrested in maintaining and I'm scared for anyone that decides to use it as it doesn't support null-safety and isn't tested apart from mediasoup demo. 

I can create a PR, but I don't recommend publishing on pub.dev. It might lead to a lot of issues and user frustration.

To be honest, no one should be using protoo client in dart/flutter anyway as there are much better and more stable signaling frameworks for WebRTC (Socket.IO for example)

**Comment by ritvij14** [comment]
I went through the comments on #4, so I will send a PR from my end. And yes I added null-safety 👍🏻

**Comment by ZackMitkin** [comment]
> I went through the comments on #4, so I will send a PR from my end. And yes I added null-safety 👍🏻

Great to hear! I had a peak at your work so far, it looks really promising. Thanks for taking the time :)

**Comment by ritvij14** [comment]
Hey @cloudwebrtc, the PR has been merged. I would really appreciate if you could drop me a ping when you release the updated version, I will forward it to the team I am a part of, so that we could continue with releasing a project we are working on.

**Comment by cloudwebrtc** [comment]
@ritvij14 uploaded
https://pub.dev/packages/protoo_client/versions

**Comment by ritvij14** [comment]
Thanks @cloudwebrtc!
