### ISSUE TITLE
Feature request handling RECONNECT

### ISSUE THREAD

**Issue by fullflash** [cloudwebrtc/dart-protoo-client#7]
thanks for this great package.
it would be awesome if this package also has a reconnect feature.

**Comment by ZackMitkin** [comment]
This library is just to port the protoo client similar to javascript [check here](https://protoo.versatica.com/#protoo)

So building an automatic reconnect into this library would steer it away from being a port of js proto client.

I think the intended way to implement reconnect is to just listen for `peer.on('close' ...`) and re-create the connection.
